name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: rustfmt
      - name: Format
        uses: actions-rust-lang/rustfmt@v1
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: clippy
      - name: Install Components
        uses: taiki-e/install-action@v2
        with:
          tool: sarif-fmt,clippy-sarif
      - name: Run Clippy
        run: cargo clippy --all --no-deps --all-features --message-format=json -- -W clippy::todo | sort | uniq | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload Clippy Results
        uses: github/codeql-action/upload-sarif@v4.38.0
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: llvm-tools
      - name: Install Components
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Run Tests with Coverage
        run: cargo llvm-cov test --no-fail-fast --all-features --lcov --output-path lcov.info
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v7
        with:
          name: lcov
          path: lcov.info
          retention-days: 1
      - name: Format Test Coverages
        run: |
          awk '/SF:/{p=1; b=$0; next} p{b=b RS $0} /LF:/{f=$2} /LH:/{h=$2} /end_of_record/{if(f!=h) print b; p=0}' FS=: lcov.info > lcov_formatted.info
          sed -i "s|$GITHUB_WORKSPACE/||g" lcov_formatted.info
      - name: Write Coverage to Summary
        uses: livewing/lcov-job-summary@v1.3.0
        with:
          lcov: lcov.info

  audit:
    name: Audit Cargo Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
