name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: stable
          components: clippy, rustfmt, llvm-tools
      - name: Install Components
        uses: taiki-e/install-action@v2
        with:
          tool: clippy-sarif,sarif-fmt,cargo-llvm-cov
      - name: Build Dev
        run: cargo build --all --verbose
      - name: Run Tests
        run: cargo test --all
      - name: Clippy
        run: cargo clippy --all --no-deps --all-features --message-format=json -- -W clippy::todo | sort | uniq | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload Clippy Results
        uses: github/codeql-action/upload-sarif@v4.38.0
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
      - name: Formatting
        uses: actions-rust-lang/rustfmt@v1
      - name: Generate Coverage Output
        run: cargo llvm-cov test --no-fail-fast --all-features --lcov --output-path lcov_raw.info
      - name: Format Test Coverages
        run: |
          awk '/SF:/{p=1; b=$0; next} p{b=b RS $0} /LF:/{f=$2} /LH:/{h=$2} /end_of_record/{if(f!=h) print b; p=0}' FS=: lcov_raw.info > lcov.info
          sed -i "s|$GITHUB_WORKSPACE/||g" lcov.info
      - name: Upload Coverages to Job Summary
        uses: livewing/lcov-job-summary@v1.3.0
        with:
          lcov: lcov.info
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v7
        with:
          name: lcov
          path: lcov_raw.info
          retention-days: 1
